version: '3'

networks:
  guessgame-network:
    driver: bridge

services:

  guessgame-postgres:
    image: postgres:15
    container_name: guessgame-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - guessgame-network

  guessgame-api:
    build:
      context: ./guessgame-api
      dockerfile: Dockerfile.dev
    container_name: guessgame-api
    restart: always
    volumes:
      - ./guessgame-api/:/usr/src/workspace/guessgame-api
    networks:
      - guessgame-network

  guessgame-ui:
    build:
      context: ./guessgame-ui
      dockerfile: Dockerfile.dev
    container_name: guessgame-ui
    restart: always
    environment:
      REACT_APP_BACKEND_URL: http://localhost/api
    volumes:
      - ./guessgame-ui/:/usr/src/workspace/guessgame-ui
    networks:
      - guessgame-network

  nginx:
    image: nginx:latest
    container_name: guessgame-nginx
    restart: always
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - guessgame-network
    depends_on:
      - guessgame-api
      - guessgame-ui